### ISSUE TITLE
Build Error after floating upgrade to 3.5.5

### ISSUE THREAD

**Issue by scottkidder** [broccolijs/broccoli-concat#131] opened 2018-07-25 14:44 UTC
While upgrading another dependency yarn decided to upgrade broccoli-concat to 3.5.0. I have many dependencies with broccoli-concat@^3.2.2 so this seems to be valid. On build I get the following error that I believe has something to do with ember-fetch.

```
 ~/dev/project1  master ●  ember build
cleaning up...
Build failed.
Build Error (SimpleConcatConcat)

ENOENT: no such file or directory, open '[BroccoliMergeTrees]/abortcontroller-polyfill-only.js'


Stack Trace and Error Report: /tmp/error.dump.b9b5ea32ef6b5a0a03e1b7c1c26ba4ec.log
```

**Comment by stefanpenner** [comment] 2018-07-25 14:54
Thanks for reporting, this is a duplicate of https://github.com/broccolijs/broccoli-concat/issues/130 and I have rolled back the offending change. 

So you should be in the clear!

**Closed by stefanpenner** 2018-07-25 14:54 UTC
